name: currency_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.5.4

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  design_system:
    path: ./design_system
  flutter_svg: ^2.0.16
  path_provider: ^2.1.5
  http: ^1.2.2
  url_launcher: ^6.3.1
  google_mobile_ads: ^5.2.0
  firebase_core: ^3.9.0
  firebase_remote_config: ^5.2.0
  shorebird_code_push: ^1.1.6
  firebase_analytics: ^11.3.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
